//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEntidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.TipoEdificio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.TipoUnidad))]
    public partial class TipoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> AtaqueField;
        
        private System.Nullable<int> DefensaField;
        
        private int IdField;
        
        private string ImagenField;
        
        private string NombreField;
        
        private System.Nullable<int> TiempoConstruccionField;
        
        private System.Nullable<int> VidaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ataque
        {
            get
            {
                return this.AtaqueField;
            }
            set
            {
                this.AtaqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Defensa
        {
            get
            {
                return this.DefensaField;
            }
            set
            {
                this.DefensaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TiempoConstruccion
        {
            get
            {
                return this.TiempoConstruccionField;
            }
            set
            {
                this.TiempoConstruccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vida
        {
            get
            {
                return this.VidaField;
            }
            set
            {
                this.VidaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEdificio", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TipoEdificio : Shared.Entities.TipoEntidad
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUnidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TipoUnidad : Shared.Entities.TipoEntidad
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8835/tsi1/", ConfigurationName="IServiceEntidades")]
public interface IServiceEntidades
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificio", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificioResponse")]
    void AltaTipoEdificio(Shared.Entities.TipoEntidad tipoEdificio);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidadResponse")]
    void AltaTipoUnidad(Shared.Entities.TipoEntidad tipoUnidad);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificios", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificiosResponse")]
    Shared.Entities.TipoEdificio[] GetAllTipoEdificios();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidades", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidadesResponse")]
    Shared.Entities.TipoUnidad[] GetAllTipoUnidades();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidadResponse")]
    void AsociarEdificioUnidad(Shared.Entities.TipoEdificio tipoEdificio, Shared.Entities.TipoUnidad tipoUnidad);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceEntidadesChannel : IServiceEntidades, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceEntidadesClient : System.ServiceModel.ClientBase<IServiceEntidades>, IServiceEntidades
{
    
    public ServiceEntidadesClient()
    {
    }
    
    public ServiceEntidadesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceEntidadesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceEntidadesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceEntidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AltaTipoEdificio(Shared.Entities.TipoEntidad tipoEdificio)
    {
        base.Channel.AltaTipoEdificio(tipoEdificio);
    }
    
    public void AltaTipoUnidad(Shared.Entities.TipoEntidad tipoUnidad)
    {
        base.Channel.AltaTipoUnidad(tipoUnidad);
    }
    
    public Shared.Entities.TipoEdificio[] GetAllTipoEdificios()
    {
        return base.Channel.GetAllTipoEdificios();
    }
    
    public Shared.Entities.TipoUnidad[] GetAllTipoUnidades()
    {
        return base.Channel.GetAllTipoUnidades();
    }
    
    public void AsociarEdificioUnidad(Shared.Entities.TipoEdificio tipoEdificio, Shared.Entities.TipoUnidad tipoUnidad)
    {
        base.Channel.AsociarEdificioUnidad(tipoEdificio, tipoUnidad);
    }
}
