//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCelda", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class InfoCelda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> PosXField;
        
        private System.Nullable<int> PosYField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PosX
        {
            get
            {
                return this.PosXField;
            }
            set
            {
                this.PosXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PosY
        {
            get
            {
                return this.PosYField;
            }
            set
            {
                this.PosYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteJuego", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class ClienteJuego : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string apellidoField;
        
        private string clienteIdField;
        
        private System.DateTime creacionField;
        
        private int idJuegoField;
        
        private string nombreField;
        
        private string tokenField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clienteId
        {
            get
            {
                return this.clienteIdField;
            }
            set
            {
                this.clienteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creacion
        {
            get
            {
                return this.creacionField;
            }
            set
            {
                this.creacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJuego
        {
            get
            {
                return this.idJuegoField;
            }
            set
            {
                this.idJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorBasico", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class JugadorBasico : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string NombreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoAtaque", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class InfoAtaque : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EnemigoField;
        
        private string JuegoField;
        
        private string JugadorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enemigo
        {
            get
            {
                return this.EnemigoField;
            }
            set
            {
                this.EnemigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Juego
        {
            get
            {
                return this.JuegoField;
            }
            set
            {
                this.JuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jugador
        {
            get
            {
                return this.JugadorField;
            }
            set
            {
                this.JugadorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Juego", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Juego : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Shared.Entities.Accion[] AccionesField;
        
        private Shared.Entities.DataActual DataJugadorField;
        
        private int EstadoField;
        
        private int IdField;
        
        private int IdDisenadorField;
        
        private int IdJugadorField;
        
        private string ImagenField;
        
        private string NombreField;
        
        private Shared.Entities.Raza[] RazasField;
        
        private Shared.Entities.Tablero TableroField;
        
        private Shared.Entities.Tecnologia[] TecnologiasField;
        
        private Shared.Entities.TipoEdificio[] TipoEdificiosField;
        
        private Shared.Entities.TipoEntidad[] TipoEntidadField;
        
        private Shared.Entities.TipoRecurso[] TipoRecursoField;
        
        private Shared.Entities.TipoUnidad[] TipoUnidadesField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Accion[] Acciones
        {
            get
            {
                return this.AccionesField;
            }
            set
            {
                this.AccionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.DataActual DataJugador
        {
            get
            {
                return this.DataJugadorField;
            }
            set
            {
                this.DataJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDisenador
        {
            get
            {
                return this.IdDisenadorField;
            }
            set
            {
                this.IdDisenadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador
        {
            get
            {
                return this.IdJugadorField;
            }
            set
            {
                this.IdJugadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Raza[] Razas
        {
            get
            {
                return this.RazasField;
            }
            set
            {
                this.RazasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Tablero Tablero
        {
            get
            {
                return this.TableroField;
            }
            set
            {
                this.TableroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Tecnologia[] Tecnologias
        {
            get
            {
                return this.TecnologiasField;
            }
            set
            {
                this.TecnologiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TipoEdificio[] TipoEdificios
        {
            get
            {
                return this.TipoEdificiosField;
            }
            set
            {
                this.TipoEdificiosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TipoEntidad[] TipoEntidad
        {
            get
            {
                return this.TipoEntidadField;
            }
            set
            {
                this.TipoEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TipoRecurso[] TipoRecurso
        {
            get
            {
                return this.TipoRecursoField;
            }
            set
            {
                this.TipoRecursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TipoUnidad[] TipoUnidades
        {
            get
            {
                return this.TipoUnidadesField;
            }
            set
            {
                this.TipoUnidadesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataActual", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class DataActual : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoRecurso> EstadoRecursosField;
        
        private System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoData> EstadoTecnologiasField;
        
        private System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoData> EstadoUnidadesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoRecurso> EstadoRecursos
        {
            get
            {
                return this.EstadoRecursosField;
            }
            set
            {
                this.EstadoRecursosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoData> EstadoTecnologias
        {
            get
            {
                return this.EstadoTecnologiasField;
            }
            set
            {
                this.EstadoTecnologiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, Shared.Entities.EstadoData> EstadoUnidades
        {
            get
            {
                return this.EstadoUnidadesField;
            }
            set
            {
                this.EstadoUnidadesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tablero", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Tablero : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CantColumnasField;
        
        private System.Nullable<int> CantFilasField;
        
        private Shared.Entities.TableroCelda[] CeldasField;
        
        private int IdField;
        
        private System.Nullable<int> IdJuegoField;
        
        private string ImagenFondoField;
        
        private string ImagenTerrenoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantColumnas
        {
            get
            {
                return this.CantColumnasField;
            }
            set
            {
                this.CantColumnasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantFilas
        {
            get
            {
                return this.CantFilasField;
            }
            set
            {
                this.CantFilasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TableroCelda[] Celdas
        {
            get
            {
                return this.CeldasField;
            }
            set
            {
                this.CeldasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenFondo
        {
            get
            {
                return this.ImagenFondoField;
            }
            set
            {
                this.ImagenFondoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenTerreno
        {
            get
            {
                return this.ImagenTerrenoField;
            }
            set
            {
                this.ImagenTerrenoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accion", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Accion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> IdEntidadField;
        
        private System.Nullable<int> IdJuegoField;
        
        private System.Nullable<int> IdTecnologiaField;
        
        private string NombreField;
        
        private string NombreAtributoField;
        
        private Shared.Entities.Tecnologia TecnologiaField;
        
        private System.Nullable<int> ValorField;
        
        private System.Nullable<int> ValorPorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdEntidad
        {
            get
            {
                return this.IdEntidadField;
            }
            set
            {
                this.IdEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTecnologia
        {
            get
            {
                return this.IdTecnologiaField;
            }
            set
            {
                this.IdTecnologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAtributo
        {
            get
            {
                return this.NombreAtributoField;
            }
            set
            {
                this.NombreAtributoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Tecnologia Tecnologia
        {
            get
            {
                return this.TecnologiaField;
            }
            set
            {
                this.TecnologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ValorPor
        {
            get
            {
                return this.ValorPorField;
            }
            set
            {
                this.ValorPorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Raza", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Raza : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Nullable<int> IdJuegoField;
        
        private string ImagenField;
        
        private Shared.Entities.Juego JuegoField;
        
        private string NombreField;
        
        private Shared.Entities.TecnologiaDependencia[] TecnologiaDependenciasField;
        
        private Shared.Entities.TipoEdificio[] TipoEdificiosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Juego Juego
        {
            get
            {
                return this.JuegoField;
            }
            set
            {
                this.JuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TecnologiaDependencia[] TecnologiaDependencias
        {
            get
            {
                return this.TecnologiaDependenciasField;
            }
            set
            {
                this.TecnologiaDependenciasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TipoEdificio[] TipoEdificios
        {
            get
            {
                return this.TipoEdificiosField;
            }
            set
            {
                this.TipoEdificiosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tecnologia", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Tecnologia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Shared.Entities.Accion[] AccionesAsociadasField;
        
        private int IdField;
        
        private int IdEdificioField;
        
        private int IdJuegoField;
        
        private string ImagenField;
        
        private string NombreField;
        
        private Shared.Entities.TecnologiaDependencia[] TecnologiaDependenciasField;
        
        private Shared.Entities.TecnologiaRecursoCosto[] TecnologiaRecursoCostosField;
        
        private int TiempoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Accion[] AccionesAsociadas
        {
            get
            {
                return this.AccionesAsociadasField;
            }
            set
            {
                this.AccionesAsociadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEdificio
        {
            get
            {
                return this.IdEdificioField;
            }
            set
            {
                this.IdEdificioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TecnologiaDependencia[] TecnologiaDependencias
        {
            get
            {
                return this.TecnologiaDependenciasField;
            }
            set
            {
                this.TecnologiaDependenciasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.TecnologiaRecursoCosto[] TecnologiaRecursoCostos
        {
            get
            {
                return this.TecnologiaRecursoCostosField;
            }
            set
            {
                this.TecnologiaRecursoCostosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tiempo
        {
            get
            {
                return this.TiempoField;
            }
            set
            {
                this.TiempoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEdificio", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TipoEdificio : Shared.Entities.TipoEntidad
    {
        
        private Shared.Entities.RecursoAsociado[] RecursosAsociadosField;
        
        private int[] TecnologiasField;
        
        private int[] UnidadesAsociadasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.RecursoAsociado[] RecursosAsociados
        {
            get
            {
                return this.RecursosAsociadosField;
            }
            set
            {
                this.RecursosAsociadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Tecnologias
        {
            get
            {
                return this.TecnologiasField;
            }
            set
            {
                this.TecnologiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] UnidadesAsociadas
        {
            get
            {
                return this.UnidadesAsociadasField;
            }
            set
            {
                this.UnidadesAsociadasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEntidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.TipoUnidad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.TipoEdificio))]
    public partial class TipoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> AtaqueField;
        
        private Shared.Entities.Costo[] CostosField;
        
        private System.Nullable<int> DefensaField;
        
        private int IdField;
        
        private int IdJuegoField;
        
        private string ImagenField;
        
        private string NombreField;
        
        private System.Nullable<int> TiempoConstruccionField;
        
        private System.Nullable<int> VidaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ataque
        {
            get
            {
                return this.AtaqueField;
            }
            set
            {
                this.AtaqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.Costo[] Costos
        {
            get
            {
                return this.CostosField;
            }
            set
            {
                this.CostosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Defensa
        {
            get
            {
                return this.DefensaField;
            }
            set
            {
                this.DefensaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TiempoConstruccion
        {
            get
            {
                return this.TiempoConstruccionField;
            }
            set
            {
                this.TiempoConstruccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vida
        {
            get
            {
                return this.VidaField;
            }
            set
            {
                this.VidaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRecurso", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TipoRecurso : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EsFijoField;
        
        private int IdField;
        
        private int IdJuegoField;
        
        private string ImagenField;
        
        private string NombreField;
        
        private int TopeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsFijo
        {
            get
            {
                return this.EsFijoField;
            }
            set
            {
                this.EsFijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJuego
        {
            get
            {
                return this.IdJuegoField;
            }
            set
            {
                this.IdJuegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tope
        {
            get
            {
                return this.TopeField;
            }
            set
            {
                this.TopeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUnidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TipoUnidad : Shared.Entities.TipoEntidad
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecnologiaDependencia", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TecnologiaDependencia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdRazaField;
        
        private int IdTecnologiaField;
        
        private int IdTecnologiaDependeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRaza
        {
            get
            {
                return this.IdRazaField;
            }
            set
            {
                this.IdRazaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTecnologia
        {
            get
            {
                return this.IdTecnologiaField;
            }
            set
            {
                this.IdTecnologiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTecnologiaDepende
        {
            get
            {
                return this.IdTecnologiaDependeField;
            }
            set
            {
                this.IdTecnologiaDependeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecnologiaRecursoCosto", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TecnologiaRecursoCosto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CostoField;
        
        private int IdRecursoField;
        
        private int IdTecnologiaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecurso
        {
            get
            {
                return this.IdRecursoField;
            }
            set
            {
                this.IdRecursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTecnologia
        {
            get
            {
                return this.IdTecnologiaField;
            }
            set
            {
                this.IdTecnologiaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoRecurso", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class EstadoRecurso : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProduccionField;
        
        private int TotalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Produccion
        {
            get
            {
                return this.ProduccionField;
            }
            set
            {
                this.ProduccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoData", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class EstadoData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantidadField;
        
        private Shared.Entities.EstadoData.EstadoEnum EstadoField;
        
        private int TiempoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.EstadoData.EstadoEnum Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tiempo
        {
            get
            {
                return this.TiempoField;
            }
            set
            {
                this.TiempoField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="EstadoData.EstadoEnum", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
        public enum EstadoEnum : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            A = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            C = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Costo", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class Costo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdEntidadField;
        
        private int IdRecursoField;
        
        private int ValorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntidad
        {
            get
            {
                return this.IdEntidadField;
            }
            set
            {
                this.IdEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecurso
        {
            get
            {
                return this.IdRecursoField;
            }
            set
            {
                this.IdRecursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecursoAsociado", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class RecursoAsociado : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdEdificioField;
        
        private int IdRecursoField;
        
        private int ValorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEdificio
        {
            get
            {
                return this.IdEdificioField;
            }
            set
            {
                this.IdEdificioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecurso
        {
            get
            {
                return this.IdRecursoField;
            }
            set
            {
                this.IdRecursoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableroCelda", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class TableroCelda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Shared.Entities.EstadoData EstadoField;
        
        private int IdField;
        
        private System.Nullable<int> IdTableroField;
        
        private System.Nullable<int> IdTipoEdificioField;
        
        private System.Nullable<int> PosColumnaField;
        
        private System.Nullable<int> PosFilaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Shared.Entities.EstadoData Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTablero
        {
            get
            {
                return this.IdTableroField;
            }
            set
            {
                this.IdTableroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTipoEdificio
        {
            get
            {
                return this.IdTipoEdificioField;
            }
            set
            {
                this.IdTipoEdificioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PosColumna
        {
            get
            {
                return this.PosColumnaField;
            }
            set
            {
                this.PosColumnaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PosFila
        {
            get
            {
                return this.PosFilaField;
            }
            set
            {
                this.PosFilaField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8836/tsi1/", ConfigurationName="IServiceTablero")]
public interface IServiceTablero
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/JugarUnidad", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/JugarUnidadResponse")]
    void JugarUnidad(Shared.Entities.InfoCelda infoCelda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/JugarUnidad", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/JugarUnidadResponse")]
    System.Threading.Tasks.Task JugarUnidadAsync(Shared.Entities.InfoCelda infoCelda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/Accion", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/AccionResponse")]
    void Accion(string json);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/Accion", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/AccionResponse")]
    System.Threading.Tasks.Task AccionAsync(string json);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/login", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/loginResponse")]
    bool login(Shared.Entities.ClienteJuego cliente, int idJuego);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/login", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/loginResponse")]
    System.Threading.Tasks.Task<bool> loginAsync(Shared.Entities.ClienteJuego cliente, int idJuego);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/register", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/registerResponse")]
    void register(Shared.Entities.ClienteJuego cliente, int idJuego);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/register", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/registerResponse")]
    System.Threading.Tasks.Task registerAsync(Shared.Entities.ClienteJuego cliente, int idJuego);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/GetListaDeJugadoresAtacables", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/GetListaDeJugadoresAtacablesResponse")]
    Shared.Entities.JugadorBasico[] GetListaDeJugadoresAtacables(string jugadorAt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/GetListaDeJugadoresAtacables", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/GetListaDeJugadoresAtacablesResponse")]
    System.Threading.Tasks.Task<Shared.Entities.JugadorBasico[]> GetListaDeJugadoresAtacablesAsync(string jugadorAt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/IniciarAtaque", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/IniciarAtaqueResponse")]
    void IniciarAtaque(Shared.Entities.InfoAtaque info);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/IniciarAtaque", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/IniciarAtaqueResponse")]
    System.Threading.Tasks.Task IniciarAtaqueAsync(Shared.Entities.InfoAtaque info);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/GetAllDataJuego", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/GetAllDataJuegoResponse")]
    Shared.Entities.Juego GetAllDataJuego(string tenant);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/GetAllDataJuego", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/GetAllDataJuegoResponse")]
    System.Threading.Tasks.Task<Shared.Entities.Juego> GetAllDataJuegoAsync(string tenant);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/DesarrollarTecnologia", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/DesarrollarTecnologiaResponse")]
    bool DesarrollarTecnologia(string tenant, string idJugador, int idTecnologia);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/DesarrollarTecnologia", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/DesarrollarTecnologiaResponse")]
    System.Threading.Tasks.Task<bool> DesarrollarTecnologiaAsync(string tenant, string idJugador, int idTecnologia);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceTableroChannel : IServiceTablero, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceTableroClient : System.ServiceModel.ClientBase<IServiceTablero>, IServiceTablero
{
    
    public ServiceTableroClient()
    {
    }
    
    public ServiceTableroClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceTableroClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTableroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTableroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void JugarUnidad(Shared.Entities.InfoCelda infoCelda)
    {
        base.Channel.JugarUnidad(infoCelda);
    }
    
    public System.Threading.Tasks.Task JugarUnidadAsync(Shared.Entities.InfoCelda infoCelda)
    {
        return base.Channel.JugarUnidadAsync(infoCelda);
    }
    
    public void Accion(string json)
    {
        base.Channel.Accion(json);
    }
    
    public System.Threading.Tasks.Task AccionAsync(string json)
    {
        return base.Channel.AccionAsync(json);
    }
    
    public bool login(Shared.Entities.ClienteJuego cliente, int idJuego)
    {
        return base.Channel.login(cliente, idJuego);
    }
    
    public System.Threading.Tasks.Task<bool> loginAsync(Shared.Entities.ClienteJuego cliente, int idJuego)
    {
        return base.Channel.loginAsync(cliente, idJuego);
    }
    
    public void register(Shared.Entities.ClienteJuego cliente, int idJuego)
    {
        base.Channel.register(cliente, idJuego);
    }
    
    public System.Threading.Tasks.Task registerAsync(Shared.Entities.ClienteJuego cliente, int idJuego)
    {
        return base.Channel.registerAsync(cliente, idJuego);
    }
    
    public Shared.Entities.JugadorBasico[] GetListaDeJugadoresAtacables(string jugadorAt)
    {
        return base.Channel.GetListaDeJugadoresAtacables(jugadorAt);
    }
    
    public System.Threading.Tasks.Task<Shared.Entities.JugadorBasico[]> GetListaDeJugadoresAtacablesAsync(string jugadorAt)
    {
        return base.Channel.GetListaDeJugadoresAtacablesAsync(jugadorAt);
    }
    
    public void IniciarAtaque(Shared.Entities.InfoAtaque info)
    {
        base.Channel.IniciarAtaque(info);
    }
    
    public System.Threading.Tasks.Task IniciarAtaqueAsync(Shared.Entities.InfoAtaque info)
    {
        return base.Channel.IniciarAtaqueAsync(info);
    }
    
    public Shared.Entities.Juego GetAllDataJuego(string tenant)
    {
        return base.Channel.GetAllDataJuego(tenant);
    }
    
    public System.Threading.Tasks.Task<Shared.Entities.Juego> GetAllDataJuegoAsync(string tenant)
    {
        return base.Channel.GetAllDataJuegoAsync(tenant);
    }
    
    public bool DesarrollarTecnologia(string tenant, string idJugador, int idTecnologia)
    {
        return base.Channel.DesarrollarTecnologia(tenant, idJugador, idTecnologia);
    }
    
    public System.Threading.Tasks.Task<bool> DesarrollarTecnologiaAsync(string tenant, string idJugador, int idTecnologia)
    {
        return base.Channel.DesarrollarTecnologiaAsync(tenant, idJugador, idTecnologia);
    }
}
