//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.ServiceEntidades {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEntidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontEnd.ServiceEntidades.TipoEdificio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontEnd.ServiceEntidades.TipoUnidad))]
    public partial class TipoEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AtaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DefensaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TiempoConstruccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ataque {
            get {
                return this.AtaqueField;
            }
            set {
                if ((this.AtaqueField.Equals(value) != true)) {
                    this.AtaqueField = value;
                    this.RaisePropertyChanged("Ataque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Defensa {
            get {
                return this.DefensaField;
            }
            set {
                if ((this.DefensaField.Equals(value) != true)) {
                    this.DefensaField = value;
                    this.RaisePropertyChanged("Defensa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TiempoConstruccion {
            get {
                return this.TiempoConstruccionField;
            }
            set {
                if ((this.TiempoConstruccionField.Equals(value) != true)) {
                    this.TiempoConstruccionField = value;
                    this.RaisePropertyChanged("TiempoConstruccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vida {
            get {
                return this.VidaField;
            }
            set {
                if ((this.VidaField.Equals(value) != true)) {
                    this.VidaField = value;
                    this.RaisePropertyChanged("Vida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEdificio", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoEdificio : FrontEnd.ServiceEntidades.TipoEntidad {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUnidad", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoUnidad : FrontEnd.ServiceEntidades.TipoEntidad {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8835/tsi1/", ConfigurationName="ServiceEntidades.IServiceEntidades")]
    public interface IServiceEntidades {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificio", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificioResponse")]
        void AltaTipoEdificio(FrontEnd.ServiceEntidades.TipoEntidad tipoEdificio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificio", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoEdificioResponse")]
        System.Threading.Tasks.Task AltaTipoEdificioAsync(FrontEnd.ServiceEntidades.TipoEntidad tipoEdificio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidadResponse")]
        void AltaTipoUnidad(FrontEnd.ServiceEntidades.TipoEntidad tipoUnidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AltaTipoUnidadResponse")]
        System.Threading.Tasks.Task AltaTipoUnidadAsync(FrontEnd.ServiceEntidades.TipoEntidad tipoUnidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificios", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificiosResponse")]
        FrontEnd.ServiceEntidades.TipoEdificio[] GetAllTipoEdificios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificios", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoEdificiosResponse")]
        System.Threading.Tasks.Task<FrontEnd.ServiceEntidades.TipoEdificio[]> GetAllTipoEdificiosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidades", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidadesResponse")]
        FrontEnd.ServiceEntidades.TipoUnidad[] GetAllTipoUnidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidades", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/GetAllTipoUnidadesResponse")]
        System.Threading.Tasks.Task<FrontEnd.ServiceEntidades.TipoUnidad[]> GetAllTipoUnidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidadResponse")]
        void AsociarEdificioUnidad(FrontEnd.ServiceEntidades.TipoEdificio tipoEdificio, FrontEnd.ServiceEntidades.TipoUnidad tipoUnidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidad", ReplyAction="http://localhost:8835/tsi1/IServiceEntidades/AsociarEdificioUnidadResponse")]
        System.Threading.Tasks.Task AsociarEdificioUnidadAsync(FrontEnd.ServiceEntidades.TipoEdificio tipoEdificio, FrontEnd.ServiceEntidades.TipoUnidad tipoUnidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEntidadesChannel : FrontEnd.ServiceEntidades.IServiceEntidades, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEntidadesClient : System.ServiceModel.ClientBase<FrontEnd.ServiceEntidades.IServiceEntidades>, FrontEnd.ServiceEntidades.IServiceEntidades {
        
        public ServiceEntidadesClient() {
        }
        
        public ServiceEntidadesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEntidadesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEntidadesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEntidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaTipoEdificio(FrontEnd.ServiceEntidades.TipoEntidad tipoEdificio) {
            base.Channel.AltaTipoEdificio(tipoEdificio);
        }
        
        public System.Threading.Tasks.Task AltaTipoEdificioAsync(FrontEnd.ServiceEntidades.TipoEntidad tipoEdificio) {
            return base.Channel.AltaTipoEdificioAsync(tipoEdificio);
        }
        
        public void AltaTipoUnidad(FrontEnd.ServiceEntidades.TipoEntidad tipoUnidad) {
            base.Channel.AltaTipoUnidad(tipoUnidad);
        }
        
        public System.Threading.Tasks.Task AltaTipoUnidadAsync(FrontEnd.ServiceEntidades.TipoEntidad tipoUnidad) {
            return base.Channel.AltaTipoUnidadAsync(tipoUnidad);
        }
        
        public FrontEnd.ServiceEntidades.TipoEdificio[] GetAllTipoEdificios() {
            return base.Channel.GetAllTipoEdificios();
        }
        
        public System.Threading.Tasks.Task<FrontEnd.ServiceEntidades.TipoEdificio[]> GetAllTipoEdificiosAsync() {
            return base.Channel.GetAllTipoEdificiosAsync();
        }
        
        public FrontEnd.ServiceEntidades.TipoUnidad[] GetAllTipoUnidades() {
            return base.Channel.GetAllTipoUnidades();
        }
        
        public System.Threading.Tasks.Task<FrontEnd.ServiceEntidades.TipoUnidad[]> GetAllTipoUnidadesAsync() {
            return base.Channel.GetAllTipoUnidadesAsync();
        }
        
        public void AsociarEdificioUnidad(FrontEnd.ServiceEntidades.TipoEdificio tipoEdificio, FrontEnd.ServiceEntidades.TipoUnidad tipoUnidad) {
            base.Channel.AsociarEdificioUnidad(tipoEdificio, tipoUnidad);
        }
        
        public System.Threading.Tasks.Task AsociarEdificioUnidadAsync(FrontEnd.ServiceEntidades.TipoEdificio tipoEdificio, FrontEnd.ServiceEntidades.TipoUnidad tipoUnidad) {
            return base.Channel.AsociarEdificioUnidadAsync(tipoEdificio, tipoUnidad);
        }
    }
}
