//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.ServiceTablero {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8836/tsi1/", ConfigurationName="ServiceTablero.IServiceTablero")]
    public interface IServiceTablero {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/JugarUnidad", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/JugarUnidadResponse")]
        void JugarUnidad(Shared.Entities.InfoCelda infoCelda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/JugarUnidad", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/JugarUnidadResponse")]
        System.Threading.Tasks.Task JugarUnidadAsync(Shared.Entities.InfoCelda infoCelda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/Accion", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/AccionResponse")]
        void Accion(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8836/tsi1/IServiceTablero/Accion", ReplyAction="http://localhost:8836/tsi1/IServiceTablero/AccionResponse")]
        System.Threading.Tasks.Task AccionAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTableroChannel : FrontEnd.ServiceTablero.IServiceTablero, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTableroClient : System.ServiceModel.ClientBase<FrontEnd.ServiceTablero.IServiceTablero>, FrontEnd.ServiceTablero.IServiceTablero {
        
        public ServiceTableroClient() {
        }
        
        public ServiceTableroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTableroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTableroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTableroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void JugarUnidad(Shared.Entities.InfoCelda infoCelda) {
            base.Channel.JugarUnidad(infoCelda);
        }
        
        public System.Threading.Tasks.Task JugarUnidadAsync(Shared.Entities.InfoCelda infoCelda) {
            return base.Channel.JugarUnidadAsync(infoCelda);
        }
        
        public void Accion(string json) {
            base.Channel.Accion(json);
        }
        
        public System.Threading.Tasks.Task AccionAsync(string json) {
            return base.Channel.AccionAsync(json);
        }
    }
}
