//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Send", ReplyAction="http://tempuri.org/IService1/SendResponse")]
        void Send(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Send", ReplyAction="http://tempuri.org/IService1/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendLista", ReplyAction="http://tempuri.org/IService1/SendListaResponse")]
        void SendLista(string[] nombreUsuarios, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendLista", ReplyAction="http://tempuri.org/IService1/SendListaResponse")]
        System.Threading.Tasks.Task SendListaAsync(string[] nombreUsuarios, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendGrupo", ReplyAction="http://tempuri.org/IService1/SendGrupoResponse")]
        void SendGrupo(string grupo, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendGrupo", ReplyAction="http://tempuri.org/IService1/SendGrupoResponse")]
        System.Threading.Tasks.Task SendGrupoAsync(string grupo, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendUsuario", ReplyAction="http://tempuri.org/IService1/SendUsuarioResponse")]
        void SendUsuario(string usuario, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendUsuario", ReplyAction="http://tempuri.org/IService1/SendUsuarioResponse")]
        System.Threading.Tasks.Task SendUsuarioAsync(string usuario, string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BusinessLogicLayer.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BusinessLogicLayer.ServiceReference1.IService1>, BusinessLogicLayer.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string msg) {
            base.Channel.Send(msg);
        }
        
        public System.Threading.Tasks.Task SendAsync(string msg) {
            return base.Channel.SendAsync(msg);
        }
        
        public void SendLista(string[] nombreUsuarios, string msg) {
            base.Channel.SendLista(nombreUsuarios, msg);
        }
        
        public System.Threading.Tasks.Task SendListaAsync(string[] nombreUsuarios, string msg) {
            return base.Channel.SendListaAsync(nombreUsuarios, msg);
        }
        
        public void SendGrupo(string grupo, string msg) {
            base.Channel.SendGrupo(grupo, msg);
        }
        
        public System.Threading.Tasks.Task SendGrupoAsync(string grupo, string msg) {
            return base.Channel.SendGrupoAsync(grupo, msg);
        }
        
        public void SendUsuario(string usuario, string msg) {
            base.Channel.SendUsuario(usuario, msg);
        }
        
        public System.Threading.Tasks.Task SendUsuarioAsync(string usuario, string msg) {
            return base.Channel.SendUsuarioAsync(usuario, msg);
        }
    }
}
