//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8837/tsi1/", ConfigurationName="IServiceInteraccion")]
public interface IServiceInteraccion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8837/tsi1/IServiceInteraccion/Send", ReplyAction="http://localhost:8837/tsi1/IServiceInteraccion/SendResponse")]
    void Send(string msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceInteraccionChannel : IServiceInteraccion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceInteraccionClient : System.ServiceModel.ClientBase<IServiceInteraccion>, IServiceInteraccion
{
    
    public ServiceInteraccionClient()
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceInteraccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Send(string msg)
    {
        base.Channel.Send(msg);
    }
}
