//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Send", ReplyAction="http://tempuri.org/IService1/SendResponse")]
    void Send(string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendLista", ReplyAction="http://tempuri.org/IService1/SendListaResponse")]
    void SendLista(string[] nombreUsuarios, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendGrupo", ReplyAction="http://tempuri.org/IService1/SendGrupoResponse")]
    void SendGrupo(string grupo, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendUsuario", ReplyAction="http://tempuri.org/IService1/SendUsuarioResponse")]
    void SendUsuario(string usuario, string msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Send(string msg)
    {
        base.Channel.Send(msg);
    }
    
    public void SendLista(string[] nombreUsuarios, string msg)
    {
        base.Channel.SendLista(nombreUsuarios, msg);
    }
    
    public void SendGrupo(string grupo, string msg)
    {
        base.Channel.SendGrupo(grupo, msg);
    }
    
    public void SendUsuario(string usuario, string msg)
    {
        base.Channel.SendUsuario(usuario, msg);
    }
}
