//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5485
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8837/tsi1/", ConfigurationName="IServiceInteraccion")]
public interface IServiceInteraccion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8837/tsi1/IServiceInteraccion/Send", ReplyAction="http://localhost:8837/tsi1/IServiceInteraccion/SendResponse")]
    void Send(string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8837/tsi1/IServiceInteraccion/SendLista", ReplyAction="http://localhost:8837/tsi1/IServiceInteraccion/SendListaResponse")]
    void SendLista(string[] nombreUsuarios, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8837/tsi1/IServiceInteraccion/SendGrupo", ReplyAction="http://localhost:8837/tsi1/IServiceInteraccion/SendGrupoResponse")]
    void SendGrupo(string grupo, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8837/tsi1/IServiceInteraccion/SendUsuario", ReplyAction="http://localhost:8837/tsi1/IServiceInteraccion/SendUsuarioResponse")]
    void SendUsuario(string usuario, string msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceInteraccionChannel : IServiceInteraccion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceInteraccionClient : System.ServiceModel.ClientBase<IServiceInteraccion>, IServiceInteraccion
{
    
    public ServiceInteraccionClient()
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceInteraccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceInteraccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Send(string msg)
    {
        base.Channel.Send(msg);
    }
    
    public void SendLista(string[] nombreUsuarios, string msg)
    {
        base.Channel.SendLista(nombreUsuarios, msg);
    }
    
    public void SendGrupo(string grupo, string msg)
    {
        base.Channel.SendGrupo(grupo, msg);
    }
    
    public void SendUsuario(string usuario, string msg)
    {
        base.Channel.SendUsuario(usuario, msg);
    }
}
