//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Relacional.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadRecursoCostos
    {
        public int IdEdificio { get; set; }
        public int IdRecurso { get; set; }
        public int Costo { get; set; }
    
        public virtual TipoEntidad TipoEntidad { get; set; }
        public virtual TipoRecurso TipoRecurso { get; set; }
    }
}
